// eslint-disable-next-line no-shadow,import/prefer-default-export
export enum BaseClientEvent {
  LIST_BASE_CLIENTS = 'LIST_BASE_CLIENTS',
  LIST_BASE_CLIENTS_FAILURE = 'LIST_BASE_CLIENTS_FAILURE',
  VIEW_BASE_CLIENT = 'VIEW_BASE_CLIENT',
  VIEW_BASE_CLIENT_FAILURE = 'VIEW_BASE_CLIENT_FAILURE',
  CREATE_BASE_CLIENT = 'CREATE_BASE_CLIENT',
  CREATE_BASE_CLIENT_FAILURE = 'CREATE_BASE_CLIENT_FAILURE',
  UPDATE_BASE_CLIENT = 'UPDATE_BASE_CLIENT',
  UPDATE_BASE_CLIENT_FAILURE = 'UPDATE_BASE_CLIENT_FAILURE',
  UPDATE_BASE_CLIENT_DEPLOYMENT = 'UPDATE_BASE_CLIENT_DEPLOYMENT',
  UPDATE_BASE_CLIENT_DEPLOYMENT_FAILURE = 'UPDATE_BASE_CLIENT_DEPLOYMENT_FAILURE',
  CREATE_CLIENT = 'CREATE_CLIENT',
  CREATE_CLIENT_FAILURE = 'CREATE_CLIENT_FAILURE',
  DELETE_CLIENT = 'DELETE_CLIENT',
  DELETE_CLIENT_FAILURE = 'DELETE_CLIENT_FAILURE',
}
