---
# Per environment values which override defaults in hmpps-authorization/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: authorization-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://authorization-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    HMPPS_AUTHORIZATION_SERVER_URL: "https://authorization-api-dev.hmpps.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
    IS_READ_ONLY: false
    SHOW_MIGRATION_WARNING: true

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
