---
# Per environment values which override defaults in hmpps-authorization/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: authorization-stage.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://authorization-stage.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-stage.hmpps.service.justice.gov.uk/auth"
    HMPPS_AUTHORIZATION_SERVER_URL: "https://authorization-server-stage.hmpps.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api-stage.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-stage.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
